### PR TITLE
Variables

### PR DESCRIPTION
**Pull request by atreyamaj**
## Changes
Put variables for:
1. Number of cards
2. Background
3. Text Colour
4. Link Colour
5. Title Colour
6. Body Background
7. Card Font Size

## How Has This Been Tested?
We ran it on our local machines and tracked the changes in real-time, and confirmed the enhancements.

## Mentions
1. Atreya Majumdar
2. Lucas Lobo
3. Alex Wilkes

## Types of changes

- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature and improvements (non-breaking change which adds/improves functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Code Refactoring (internal change which is not user facing)
- [x] Documentation
- [ ] Test, CI, or build

## Checklist

- [X] Coding style of this project is followed
- [ ] Change in documentation is required
- [ ] Documentation has been updated accordingly 
- [ ] Unit tests have been added to cover code change

### CODE REVIEW

**Review by wrussell1999 — CHANGES_REQUESTED** [review]
This looks and works great! 

Could you add a section to the README explaining to someone new what each variable is (what it does etc) and a brief on how they can edit these to make the site their own?

**Comment by atreyamaj** [comment]
Definitely! We're on it!

**Comment by atreyamaj** [comment]
@wrussell1999 We've added some documentation to the readme. Please do let us know if there are any further changes to be made!

**Comment by atreyamaj** [comment]
@wrussell1999  We have added some documentation to the readme. Please do let us know if you can see them and if there are any further changes to be made!

**Comment by Korusuke** [comment]
Thanks for this amazing PR! Everything looks solid to me!
This is definitely going to help folks working on #53 and #55

**Comment by atreyamaj** [comment]
Thanks! We had a lot of fun working on it as well :)

**Pull request merged**
