### PR TITLE
Blog posts

### PR DESCRIPTION
**Pull request by prashi23**
## Changes
#9 

Added navigation bar to link projects with the blog.  

## How Has This Been Tested?

We ran the implemented changes in our local machines. 

## Mentions

1. Prashi Doval
2. Samuel Yuan
3. Rashi Sharma

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature and improvements (non-breaking change which adds/improves functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Code Refactoring (internal change which is not user facing)
- [ ] Documentation
- [ ] Test, CI, or build

## Checklist

- [x] Coding style of this project is followed
- [x] Change in documentation is required
- [ ] Documentation has been updated accordingly 
- [ ] Unit tests have been added to cover code change

### CODE REVIEW

**Comment by YuanSamuel** [comment]
This fixes #9

**Review by RashikaKarki — CHANGES_REQUESTED** [review]
Awesome job so far. The PR is looking really great. 

Few suggestions:
- Can you add a quick guide about how to add the blog post in the ReadMe?
- I think @YuanSamuel  is already working on this but would be great if you sync your repo upstream repo to avoid merge conflicts.
- Can you add Screenshots of changes that you made, would make it easier to review :)

**Comment by prashi23** [comment]
Added blog posts link, launch icon and documentation changes.  Here are before and after screenshots. 
Before- 
Screenshot from 2021-02-03 22-57-17

After- 
Screenshot from 2021-02-03 22-56-28

**Review by RashikaKarki — CHANGES_REQUESTED** [review]
This is looking great.
I just realized that there isn't any option to navigate back to home page or blog page from blog post page. Having that in the navbar there would be great.

**Comment by RashikaKarki** [comment]
image

**Comment by YuanSamuel** [comment]
Also changed cards UI from this:
Screen Shot 2021-02-03 at 12 18 49 PM

to this:
Screen Shot 2021-02-03 at 12 19 38 PM

**Review by RashikaKarki — APPROVED** [review]
Everything is looking great ✨

**Pull request merged**
